# Generated by Django 5.2.3 on 2025-06-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormSubmission',
            new_name='Submission',
        ),
    ]
