# Generated by Django 5.2.3 on 2025-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_formsubmission_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='secure_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
